# Generated by Django 5.1 on 2024-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='activities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='tips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
