# Generated by Django 5.1 on 2024-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_travelguide_activities_travelguide_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='img_Caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
