# Generated by Django 5.1 on 2024-08-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_travelguide_img_travelguide_img_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelguide',
            name='img_Caption',
        ),
    ]
