# Generated by Django 5.1 on 2024-08-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tour_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_package',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour_package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour_package',
            name='reviews',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
