# Generated by Django 5.1 on 2024-08-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tour_package_cost_tour_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_package',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
