# Generated by Django 5.1 on 2024-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
