# Generated by Django 4.2.15 on 2024-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blog_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa_Assitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('visa_types', models.JSONField()),
                ('visa_requirements', models.JSONField()),
                ('visa_process', models.JSONField()),
                ('additional_info', models.JSONField()),
                ('faqs', models.JSONField()),
            ],
        ),
    ]
