# Generated by Django 4.2.15 on 2024-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_visa_assitance'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_assitance',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
